---

# Instalação das dependencias do Oracle Virtualbox


- name: "Atualizando apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - repo


- name: "Instalando os pacotes de dependencias para o Virtualbox"
  apt:
    name: "{{ pacotes_virtualbox }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - deps


# Instalação do Oracle Virtualbox


- name: Importando a primeira chave do repositorio do Oracle Virtualbox
  copy:
    src: "oracle-virtualbox-2016.gpg"
    dest: "/usr/share/keyrings/oracle-virtualbox-2016.gpg"
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - repo
    - virtualbox


- name: Importando a segunda chave do repositorio do Oracle Virtualbox
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  become: true
  tags:
    - repo
    - virtualbox


- name: Adicionando o Repositorio do Oracle Virtualbox para Debian ou Ubuntu
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  template:
    src: "virtualbox_debian.list.j2"
    dest: "/etc/apt/sources.list.d/virtualbox.list"
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - repo
    - virtualbox


- name: "Adicionando o Repositorio do Oracle Virtualbox para o Linux Mint"
  when: ansible_distribution == "Linux Mint"
  template:
    src: "virtualbox_mint.list.j2"
    dest: "/etc/apt/sources.list.d/virtualbox.list"
    owner: root
    group: root
    mode: "0644"
  become: true
  tags:
    - repo
    - virtualbox


- name: "Atualizando apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - repo
    - virtualbox


# Instalação do Vagrant Virtualbox

- name: "Instalando o Oracle Virtualbox {{ virtualbox_version }}"
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: present
    update_cache: yes
  notify:
    - Adicionando usuario ao grupo 'vboxusers'
  become: true
  tags:
    - virtualbox

